type BankSampah = {
  "Nama": string,
  "Alamat": string,
  "Kelurahan": string,
  "Kecamatan": string,
  "Kapasitas": Number,
  "Volume Masuk": Number,
  "Volume Dikelola": Number,
  "Volume Sampah Diolah": Number,
  "Volume Diangkut": Number,
  "Latitude": Number,
  "Longitude": Number,
  "Jarak"?: Number
}

export const bankSampah: BankSampah[] = [
  {
    "Nama":"TPS Pasar Asemrowo",
    "Alamat":"Jl. Asemraya",
    "Kelurahan":"Asemrowo",
    "Kecamatan":"Asemrowo",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2434243,
    "Longitude":112.7034273
  },
  {
    "Nama":"TPS Jayamix",
    "Alamat":"Jl. Dupak Rukun",
    "Kelurahan":"Asemrowo",
    "Kecamatan":"Asemrowo",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2434243,
    "Longitude":112.7034273
  },
  {
    "Nama":"TPS Genting",
    "Alamat":"Jl. Genting",
    "Kelurahan":"Asemrowo",
    "Kecamatan":"Asemrowo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2434243,
    "Longitude":112.7034273
  },
  {
    "Nama":"Landasan Tambak Asri",
    "Alamat":"Jl. Tambak Asri",
    "Kelurahan":"Genting Kalianak",
    "Kecamatan":"Asemrowo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2366584,
    "Longitude":112.7058987
  },
  {
    "Nama":"TPS Greges",
    "Alamat":"Jl. Greges Kalianak",
    "Kelurahan":"Tambak Sarioso",
    "Kecamatan":"Asemrowo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2364589,
    "Longitude":112.6811871
  },
  {
    "Nama":"TPS Kandangan",
    "Alamat":"Jl. Kandangan",
    "Kelurahan":"Kandangan",
    "Kecamatan":"Benowo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2495909,
    "Longitude":112.6502826
  },
  {
    "Nama":"TPS Griya Citra Asri",
    "Alamat":"Jl. Perum Griya Citra Asri",
    "Kelurahan":"Kandangan",
    "Kecamatan":"Benowo",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2495909,
    "Longitude":112.6502826
  },
  {
    "Nama":"TPS Rusunawa Romokalisari",
    "Alamat":"Jl. Rusunawa Romokalisari",
    "Kelurahan":"Romokalisari",
    "Kecamatan":"Benowo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2049763,
    "Longitude":112.6394385
  },
  {
    "Nama":"TPS Bandarejo Sememi",
    "Alamat":"Jl. Bandarejo Pasar Sememi",
    "Kelurahan":"Sememi",
    "Kecamatan":"Benowo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2465629,
    "Longitude":112.6420176
  },
  {
    "Nama":"Pemilahan TPS 3R Tambak Oso Wilangun",
    "Alamat":"Jl. Tambak Oso Wilangun",
    "Kelurahan":"Tambak Oso Wilangun",
    "Kecamatan":"Benowo",
    "Kapasitas":20.0,
    "Volume Masuk":1175.0,
    "Volume Dikelola":1175.0,
    "Volume Sampah Diolah":466.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.2190708,
    "Longitude":112.6544175
  },
  {
    "Nama":"TPS Sulung Kali",
    "Alamat":"Jl. Sulung Kali",
    "Kelurahan":"Alon Alon Contong",
    "Kecamatan":"Bubutan",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.2500402,
    "Longitude":112.737988
  },
  {
    "Nama":"TPS Penghela",
    "Alamat":"Jl. Penghela",
    "Kelurahan":"Bubutan",
    "Kecamatan":"Bubutan",
    "Kapasitas":33.0,
    "Volume Masuk":33.0,
    "Volume Dikelola":30.0,
    "Volume Sampah Diolah":33.0,
    "Volume Diangkut":33.0,
    "Latitude":-7.2501071,
    "Longitude":112.7330795
  },
  {
    "Nama":"TPS Pirngadi",
    "Alamat":"Jl. Pirngadi",
    "Kelurahan":"Bubutan",
    "Kecamatan":"Bubutan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2501071,
    "Longitude":112.7330795
  },
  {
    "Nama":"TPS Dupak Prahu",
    "Alamat":"Jl. Babadan Dupak",
    "Kelurahan":"Jepara",
    "Kecamatan":"Bubutan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2413618,
    "Longitude":112.7263961
  },
  {
    "Nama":"TPS Kalibutuh",
    "Alamat":"Jl. Raya Demak",
    "Kelurahan":"Tembok Dukuh",
    "Kecamatan":"Bubutan",
    "Kapasitas":52.8,
    "Volume Masuk":52.8,
    "Volume Dikelola":52.8,
    "Volume Sampah Diolah":52.8,
    "Volume Diangkut":52.8,
    "Latitude":-7.2541088,
    "Longitude":112.7217094
  },
  {
    "Nama":"Rukom Tambak Deres",
    "Alamat":"Jl. Kyai Tambak Deres",
    "Kelurahan":"Bulak",
    "Kecamatan":"Bulak",
    "Kapasitas":8.0,
    "Volume Masuk":0.0,
    "Volume Dikelola":0.0,
    "Volume Sampah Diolah":0.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.2310504,
    "Longitude":112.7792544
  },
  {
    "Nama":"TPS Tambak Deres",
    "Alamat":"Jl. Tambak Deres",
    "Kelurahan":"Bulak",
    "Kecamatan":"Bulak",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2310504,
    "Longitude":112.7792544
  },
  {
    "Nama":"TPS Bukit Mas",
    "Alamat":"Jl. Puncak Bukit Mas - Dukuh Pakis",
    "Kelurahan":"Dukuh Pakis",
    "Kecamatan":"Dukuh Pakis",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2942104,
    "Longitude":112.7121307
  },
  {
    "Nama":"TPS Gunungsari Yani Golf",
    "Alamat":"Jl. Golf V",
    "Kelurahan":"Gunung Sari",
    "Kecamatan":"Dukuh Pakis",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2997877,
    "Longitude":112.7148852
  },
  {
    "Nama":"TPS Jogoloyo",
    "Alamat":"Jl. Jogoloyo",
    "Kelurahan":"Gunung Sari",
    "Kecamatan":"Dukuh Pakis",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2997877,
    "Longitude":112.7148852
  },
  {
    "Nama":"Rukom Gunungsari",
    "Alamat":"Jl. Golf No. 4 Komplek Marinir Gunungsari",
    "Kelurahan":"Gunungsari",
    "Kecamatan":"Dukuh Pakis",
    "Kapasitas":14.0,
    "Volume Masuk":3.3,
    "Volume Dikelola":3.3,
    "Volume Sampah Diolah":3.3,
    "Volume Diangkut":0.0,
    "Latitude":-7.2997877,
    "Longitude":112.7148852
  },
  {
    "Nama":"TPS Pradah Kali Kendal",
    "Alamat":"Jl. Darmo Permai Selatan",
    "Kelurahan":"Pradah Kali Kendal",
    "Kecamatan":"Dukuh Pakis",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2844204,
    "Longitude":112.692294
  },
  {
    "Nama":"TPS Dukuh Menanggal Ikip",
    "Alamat":"Jl. Dukuh Menanggal XII",
    "Kelurahan":"Dukuh Menanggal",
    "Kecamatan":"Gayungan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3439578,
    "Longitude":112.7281163
  },
  {
    "Nama":"Rukom Gayungsari",
    "Alamat":"Jl. Gayungsari IV",
    "Kelurahan":"Gayungan",
    "Kecamatan":"Gayungan",
    "Kapasitas":8.0,
    "Volume Masuk":2.8,
    "Volume Dikelola":2.8,
    "Volume Sampah Diolah":2.8,
    "Volume Diangkut":0.0,
    "Latitude":-7.3337207,
    "Longitude":112.7246852
  },
  {
    "Nama":"TPS Gayungsari",
    "Alamat":"Jl. Gayungsari No. 4",
    "Kelurahan":"Gayungan",
    "Kecamatan":"Gayungan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3337207,
    "Longitude":112.7246852
  },
  {
    "Nama":"TPS Kebonsari Makam",
    "Alamat":"Jl. Kebonsari Makam",
    "Kelurahan":"Kebonsari",
    "Kecamatan":"Gayungan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3297146,
    "Longitude":112.7222116
  },
  {
    "Nama":"TPS Gayungpring",
    "Alamat":"Jl. Gayungsari No. 4",
    "Kelurahan":"Menanggal",
    "Kecamatan":"Gayungan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3399132,
    "Longitude":112.723408
  },
  {
    "Nama":"TPS Menanggal YKP",
    "Alamat":"Jl. Menanggal YKP",
    "Kelurahan":"Menanggal",
    "Kecamatan":"Gayungan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3399132,
    "Longitude":112.723408
  },
  {
    "Nama":"TPS Pagesangan",
    "Alamat":"Jl. Pagesangan",
    "Kelurahan":"Pagesangan",
    "Kecamatan":"Gayungan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.338323,
    "Longitude":112.7168019
  },
  {
    "Nama":"TPS Kayon",
    "Alamat":"Jl. Kayon",
    "Kelurahan":"Embong Kaliasin",
    "Kecamatan":"Genteng",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.2677425,
    "Longitude":112.7444055
  },
  {
    "Nama":"TPS Pasar Genteng",
    "Alamat":"Jl. Genteng Besar",
    "Kelurahan":"Genteng",
    "Kecamatan":"Genteng",
    "Kapasitas":26.0,
    "Volume Masuk":26.0,
    "Volume Dikelola":26.0,
    "Volume Sampah Diolah":26.0,
    "Volume Diangkut":26.0,
    "Latitude":-7.2585893,
    "Longitude":112.7386017
  },
  {
    "Nama":"TPS Simpang Dukuh",
    "Alamat":"Jl. Simpang Dukuh",
    "Kelurahan":"Genteng",
    "Kecamatan":"Genteng",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.2585893,
    "Longitude":112.7386017
  },
  {
    "Nama":"TPS Srikana",
    "Alamat":"Jl. Srikana",
    "Kelurahan":"Airlangga",
    "Kecamatan":"Gubeng",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.2728763,
    "Longitude":112.7573363
  },
  {
    "Nama":"Rukom Srikana",
    "Alamat":"Jl. Srikana - Universitas Airlangga",
    "Kelurahan":"Airlangga",
    "Kecamatan":"Gubeng",
    "Kapasitas":14.0,
    "Volume Masuk":0.1,
    "Volume Dikelola":0.1,
    "Volume Sampah Diolah":0.1,
    "Volume Diangkut":0.0,
    "Latitude":-7.2728763,
    "Longitude":112.7573363
  },
  {
    "Nama":"TPS Bratang",
    "Alamat":"Jl. Bratang Binangun",
    "Kelurahan":"Barata Jaya",
    "Kecamatan":"Gubeng",
    "Kapasitas":52.8,
    "Volume Masuk":52.8,
    "Volume Dikelola":52.8,
    "Volume Sampah Diolah":52.8,
    "Volume Diangkut":52.8,
    "Latitude":-7.3052645,
    "Longitude":112.7603334
  },
  {
    "Nama":"TPS Barata Jaya",
    "Alamat":"Jl. Baratajaya",
    "Kelurahan":"Baratajaya",
    "Kecamatan":"Gubeng",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2960594,
    "Longitude":112.7594578
  },
  {
    "Nama":"Rukom Bratang",
    "Alamat":"Jl. Manyar",
    "Kelurahan":"Baratajaya",
    "Kecamatan":"Gubeng",
    "Kapasitas":40.0,
    "Volume Masuk":11.4,
    "Volume Dikelola":11.4,
    "Volume Sampah Diolah":11.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.2960594,
    "Longitude":112.7594578
  },
  {
    "Nama":"Pemilahan Bratang",
    "Alamat":"Jl. Manyar (Taman Flora)",
    "Kelurahan":"Baratajaya",
    "Kecamatan":"Gubeng",
    "Kapasitas":5.0,
    "Volume Masuk":850.1,
    "Volume Dikelola":850.1,
    "Volume Sampah Diolah":470.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.2960594,
    "Longitude":112.7594578
  },
  {
    "Nama":"TPS Kangean",
    "Alamat":"Jl. Kangean",
    "Kelurahan":"Gubeng",
    "Kecamatan":"Gubeng",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.2725255,
    "Longitude":112.7489564
  },
  {
    "Nama":"TPS Pasar Pucang",
    "Alamat":"Jl. Pasar Pucang Anom",
    "Kelurahan":"Gubeng",
    "Kecamatan":"Gubeng",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2725255,
    "Longitude":112.7489564
  },
  {
    "Nama":"TPS Kaliwaron",
    "Alamat":"Jl. Kaliwaron",
    "Kelurahan":"Mojo",
    "Kecamatan":"Gubeng",
    "Kapasitas":29.7,
    "Volume Masuk":29.7,
    "Volume Dikelola":29.7,
    "Volume Sampah Diolah":29.7,
    "Volume Diangkut":29.7,
    "Latitude":-7.2713958,
    "Longitude":112.767093
  },
  {
    "Nama":"Rukom Menur",
    "Alamat":"Jl. Menur",
    "Kelurahan":"Mojo",
    "Kecamatan":"Gubeng",
    "Kapasitas":20.0,
    "Volume Masuk":4.8,
    "Volume Dikelola":4.8,
    "Volume Sampah Diolah":3.3,
    "Volume Diangkut":0.0,
    "Latitude":-7.2713958,
    "Longitude":112.767093
  },
  {
    "Nama":"TPS Mojoarum",
    "Alamat":"Jl. Mojoarum",
    "Kelurahan":"Mojo",
    "Kecamatan":"Gubeng",
    "Kapasitas":23.1,
    "Volume Masuk":23.1,
    "Volume Dikelola":23.1,
    "Volume Sampah Diolah":23.1,
    "Volume Diangkut":23.1,
    "Latitude":-7.2713958,
    "Longitude":112.767093
  },
  {
    "Nama":"TPS Kalibokor",
    "Alamat":"Jl. Kalibokor",
    "Kelurahan":"Pucang Sewu",
    "Kecamatan":"Gubeng",
    "Kapasitas":33.0,
    "Volume Masuk":33.0,
    "Volume Dikelola":33.0,
    "Volume Sampah Diolah":33.0,
    "Volume Diangkut":33.0,
    "Latitude":-7.2882032,
    "Longitude":112.7519619
  },
  {
    "Nama":"TPS 3R Gununganyar",
    "Alamat":"Jl. Gununganyar",
    "Kelurahan":"Gunung Anyar",
    "Kecamatan":"Gunung Anyar",
    "Kapasitas":20.0,
    "Volume Masuk":257.0,
    "Volume Dikelola":257.0,
    "Volume Sampah Diolah":135.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.3390803,
    "Longitude":112.7890957
  },
  {
    "Nama":"TPS Purimas",
    "Alamat":"Jl. Perum Purimas Gunung Anyar",
    "Kelurahan":"Gunung Anyar",
    "Kecamatan":"Gunung Anyar",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3390803,
    "Longitude":112.7890957
  },
  {
    "Nama":"TPS Wiguna Timur",
    "Alamat":"Jl. Wiguna Timur",
    "Kelurahan":"Gunung Anyar",
    "Kecamatan":"Gunung Anyar",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3390803,
    "Longitude":112.7890957
  },
  {
    "Nama":"TPS Metro Merr",
    "Alamat":"Jl. Sukarno Hatta (Pojok Merr Gunung Anyar)",
    "Kelurahan":"Rungkut Kidul",
    "Kecamatan":"Gunung Anyar",
    "Kapasitas":9.9,
    "Volume Masuk":9.9,
    "Volume Dikelola":9.9,
    "Volume Sampah Diolah":9.9,
    "Volume Diangkut":9.9,
    "Latitude":-7.3312906,
    "Longitude":112.7687712
  },
  {
    "Nama":"TPS Rungkut Menanggal",
    "Alamat":"Jl. Rungkut Menanggal Harapan",
    "Kelurahan":"Rungkut Menanggal",
    "Kecamatan":"Gunung Anyar",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3381011,
    "Longitude":112.7680711
  },
  {
    "Nama":"TPS Jambangan",
    "Alamat":"Jl. Jambangan",
    "Kelurahan":"Jambangan",
    "Kecamatan":"Jambangan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3189386,
    "Longitude":112.7146393
  },
  {
    "Nama":"Rukom Jangkar",
    "Alamat":"Jl. Jambangan Baru VI (Taman Jangkar)",
    "Kelurahan":"Jambangan",
    "Kecamatan":"Jambangan",
    "Kapasitas":8.0,
    "Volume Masuk":2.9,
    "Volume Dikelola":2.9,
    "Volume Sampah Diolah":2.9,
    "Volume Diangkut":0.0,
    "Latitude":-7.3189386,
    "Longitude":112.7146393
  },
  {
    "Nama":"Pemilahan Pdu Jambangan",
    "Alamat":"Jl. Jambangan Kebon Agung",
    "Kelurahan":"Jambangan",
    "Kecamatan":"Jambangan",
    "Kapasitas":20.0,
    "Volume Masuk":2003.7,
    "Volume Dikelola":2003.7,
    "Volume Sampah Diolah":1370.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.3189386,
    "Longitude":112.7146393
  },
  {
    "Nama":"Rukom Jambangan",
    "Alamat":"Jl. Kebon Agung No. 1",
    "Kelurahan":"Jambangan",
    "Kecamatan":"Jambangan",
    "Kapasitas":40.0,
    "Volume Masuk":13.6,
    "Volume Dikelola":13.6,
    "Volume Sampah Diolah":13.6,
    "Volume Diangkut":0.0,
    "Latitude":-7.3189386,
    "Longitude":112.7146393
  },
  {
    "Nama":"Rukom Bibis Karah",
    "Alamat":"Jl. Depo Sampah Bibis Karah",
    "Kelurahan":"Karah",
    "Kecamatan":"Jambangan",
    "Kapasitas":14.0,
    "Volume Masuk":2.2,
    "Volume Dikelola":2.2,
    "Volume Sampah Diolah":2.2,
    "Volume Diangkut":0.0,
    "Latitude":-7.3148614,
    "Longitude":112.720556
  },
  {
    "Nama":"TPS Bibis Karah",
    "Alamat":"Jl. Karah",
    "Kelurahan":"Karah",
    "Kecamatan":"Jambangan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3148614,
    "Longitude":112.720556
  },
  {
    "Nama":"TPS Pasar Kebonsari",
    "Alamat":"Jl. Kebonsari Tengah",
    "Kelurahan":"Kebonsari",
    "Kecamatan":"Jambangan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3265821,
    "Longitude":112.7149118
  },
  {
    "Nama":"TPS Ketintang Baru Selatan",
    "Alamat":"Jl. Ketintang Selatan",
    "Kelurahan":"Ketintang",
    "Kecamatan":"Jambangan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3146051,
    "Longitude":112.721242
  },
  {
    "Nama":"TPS 3R Karangpilang",
    "Alamat":"Jl. Mastrip Gg. Surya",
    "Kelurahan":"Karang Pilang",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":20.0,
    "Volume Masuk":0.0,
    "Volume Dikelola":0.0,
    "Volume Sampah Diolah":0.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.3389592,
    "Longitude":112.6899507
  },
  {
    "Nama":"TPS Karang Pilang Marinir (Ps. Hewan)",
    "Alamat":"Jl. Bumi Marinir",
    "Kelurahan":"Karangpilang",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3396887,
    "Longitude":112.6892263
  },
  {
    "Nama":"TPS Kebraon",
    "Alamat":"Jl. Kebraon Selatan",
    "Kelurahan":"Kebraon",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3296178,
    "Longitude":112.7004257
  },
  {
    "Nama":"TPS Kemlaten",
    "Alamat":"Jl. Mastrip",
    "Kelurahan":"Kedurus",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3196971,
    "Longitude":112.7059449
  },
  {
    "Nama":"TPS Bogangin",
    "Alamat":"Jl. Mastrip",
    "Kelurahan":"Kedurus",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3196971,
    "Longitude":112.7059449
  },
  {
    "Nama":"TPS Pasar Kedurus",
    "Alamat":"Jl. Pasar Kedurus",
    "Kelurahan":"Kedurus",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3196971,
    "Longitude":112.7059449
  },
  {
    "Nama":"TPS Rusunawa Warugunung",
    "Alamat":"Jl. Mastrip Warugunung",
    "Kelurahan":"Warugunung",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3419619,
    "Longitude":112.674171
  },
  {
    "Nama":"TPS 3R Warugunung",
    "Alamat":"Jl. Mastrip Warugunung",
    "Kelurahan":"Warugunung",
    "Kecamatan":"Karang Pilang",
    "Kapasitas":20.0,
    "Volume Masuk":2421.1,
    "Volume Dikelola":2421.1,
    "Volume Sampah Diolah":1139.3,
    "Volume Diangkut":0.0,
    "Latitude":-7.3419619,
    "Longitude":112.674171
  },
  {
    "Nama":"TPS Kedung Anyar",
    "Alamat":"Jl. Kedung Anyar",
    "Kelurahan":"Kedungdoro",
    "Kecamatan":"Kedungdoro",
    "Kapasitas":33.0,
    "Volume Masuk":33.0,
    "Volume Dikelola":33.0,
    "Volume Sampah Diolah":33.0,
    "Volume Diangkut":33.0,
    "Latitude":-7.2650663,
    "Longitude":112.730476
  },
  {
    "Nama":"TPS Memet",
    "Alamat":"Jl. Memet Sastro Wirya",
    "Kelurahan":"Bulak",
    "Kecamatan":"Kenjeran",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2058731,
    "Longitude":112.7639148
  },
  {
    "Nama":"TPS Bulak Banteng Podomoro",
    "Alamat":"Jl. Bulak Banteng Pasar Podomoro",
    "Kelurahan":"Bulak Banteng",
    "Kecamatan":"Kenjeran",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.2090123,
    "Longitude":112.7664264
  },
  {
    "Nama":"TPS Dukuh Bulak Banteng",
    "Alamat":"Jl. Bulak Banteng Sekolahan",
    "Kelurahan":"Bulak Banteng",
    "Kecamatan":"Kenjeran",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2090123,
    "Longitude":112.7664264
  },
  {
    "Nama":"TPS Bulak Banteng Timur",
    "Alamat":"Jl. Bulak Banteng Timur",
    "Kelurahan":"Bulak Banteng",
    "Kecamatan":"Kenjeran",
    "Kapasitas":16.0,
    "Volume Masuk":16.0,
    "Volume Dikelola":16.0,
    "Volume Sampah Diolah":16.0,
    "Volume Diangkut":16.0,
    "Latitude":-7.2090123,
    "Longitude":112.7664264
  },
  {
    "Nama":"Landasan Platuk",
    "Alamat":"Jl. Dk Bulak Banteng",
    "Kelurahan":"Bulak Banteng",
    "Kecamatan":"Kenjeran",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2090123,
    "Longitude":112.7664264
  },
  {
    "Nama":"TPS 3R Kedungcowek",
    "Alamat":"Jl. Raya Kedung Cowek No. 1 (Jl. Akses Jl. Lingkar Luar Timur)",
    "Kelurahan":"Kedung Cowek",
    "Kecamatan":"Kenjeran",
    "Kapasitas":20.0,
    "Volume Masuk":675.5,
    "Volume Dikelola":675.5,
    "Volume Sampah Diolah":349.2,
    "Volume Diangkut":0.0,
    "Latitude":-7.2188043,
    "Longitude":112.7777012
  },
  {
    "Nama":"TPS Tanah Kali Kedinding",
    "Alamat":"Jl. Tanah Kali Kedinding",
    "Kelurahan":"Kedung Cowek",
    "Kecamatan":"Kenjeran",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2188043,
    "Longitude":112.7777012
  },
  {
    "Nama":"TPS THP Kenjeran",
    "Alamat":"Jl. Kenjeran",
    "Kelurahan":"Kenjeran",
    "Kecamatan":"Kenjeran",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2339556,
    "Longitude":112.7848076
  },
  {
    "Nama":"TPS Sidotopo Wetan Pasar",
    "Alamat":"Pasar Sidotopo Wetan",
    "Kelurahan":"Sidotopo Wetan",
    "Kecamatan":"Kenjeran",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2214774,
    "Longitude":112.7626077
  },
  {
    "Nama":"TPS 3R Tambakwedi",
    "Alamat":"Jl. Kedung Cowek - Suramadu",
    "Kelurahan":"Tambak Wedi",
    "Kecamatan":"Kenjeran",
    "Kapasitas":20.0,
    "Volume Masuk":20.0,
    "Volume Dikelola":20.0,
    "Volume Sampah Diolah":20.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.2113642,
    "Longitude":112.7749931
  },
  {
    "Nama":"TPS Tambak Wedi",
    "Alamat":"Jl. Tambak Wedi",
    "Kelurahan":"Tambak Wedi",
    "Kecamatan":"Kenjeran",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2113642,
    "Longitude":112.7749931
  },
  {
    "Nama":"Rukom Tambak Wedi",
    "Alamat":"Jl. Tambak Wedi Baru",
    "Kelurahan":"Tambak Wedi",
    "Kecamatan":"Kenjeran",
    "Kapasitas":8.0,
    "Volume Masuk":4.4,
    "Volume Dikelola":4.4,
    "Volume Sampah Diolah":4.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.2113642,
    "Longitude":112.7749931
  },
  {
    "Nama":"TPS Legundi",
    "Alamat":"Jl. Anggrek",
    "Kelurahan":"Ketabang",
    "Kecamatan":"Ketabang",
    "Kapasitas":29.7,
    "Volume Masuk":29.7,
    "Volume Dikelola":29.7,
    "Volume Sampah Diolah":29.7,
    "Volume Diangkut":29.7,
    "Latitude":-7.2577755,
    "Longitude":112.7483131
  },
  {
    "Nama":"TPS Dupak Bangunsari",
    "Alamat":"Dupak Bangunsari",
    "Kelurahan":"Dupak",
    "Kecamatan":"Krembangan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2409083,
    "Longitude":112.7184585
  },
  {
    "Nama":"TPS Dupak Bandarejo",
    "Alamat":"Dupak Bndarejo",
    "Kelurahan":"Dupak",
    "Kecamatan":"Krembangan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2409083,
    "Longitude":112.7184585
  },
  {
    "Nama":"TPS Krembangan Barat",
    "Alamat":"Jl. Krembangan Barat",
    "Kelurahan":"Krembangan Selatan",
    "Kecamatan":"Krembangan",
    "Kapasitas":42.0,
    "Volume Masuk":42.0,
    "Volume Dikelola":42.0,
    "Volume Sampah Diolah":42.0,
    "Volume Diangkut":42.0,
    "Latitude":-7.237894,
    "Longitude":112.7344893
  },
  {
    "Nama":"TPS Morokrembangan",
    "Alamat":"Jl. Gadukan Utara",
    "Kelurahan":"Morokrembangan",
    "Kecamatan":"Krembangan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2281143,
    "Longitude":112.7163129
  },
  {
    "Nama":"TPS Mbah Ratu",
    "Alamat":"Jl. Gresik",
    "Kelurahan":"Morokrembangan",
    "Kecamatan":"Krembangan",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2281143,
    "Longitude":112.7163129
  },
  {
    "Nama":"Rukom Mbah Ratu",
    "Alamat":"Jl. Gresik Gadukan Timur (Makam Mbah Ratu)",
    "Kelurahan":"Morokrembangan",
    "Kecamatan":"Krembangan",
    "Kapasitas":8.0,
    "Volume Masuk":1.5,
    "Volume Dikelola":1.5,
    "Volume Sampah Diolah":1.5,
    "Volume Diangkut":0.0,
    "Latitude":-7.2281143,
    "Longitude":112.7163129
  },
  {
    "Nama":"TPS Brimob Ppi",
    "Alamat":"Jl. Sedayu No. 2",
    "Kelurahan":"Morokrembangan",
    "Kecamatan":"Krembangan",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2281143,
    "Longitude":112.7163129
  },
  {
    "Nama":"TPS Tanjung Sadari",
    "Alamat":"Jl. Tanjung Sadari",
    "Kelurahan":"Perak Barat",
    "Kecamatan":"Krembangan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2201466,
    "Longitude":112.7248649
  },
  {
    "Nama":"TPS Bangkingan",
    "Alamat":"Jl. Raya Bangkingan",
    "Kelurahan":"Bangkingan",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.3228277,
    "Longitude":112.6572924
  },
  {
    "Nama":"TPS Aspol Bangkingan",
    "Alamat":"Jl. Raya Bangkingan (Aspol)",
    "Kelurahan":"Bangkingan",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3228277,
    "Longitude":112.6572924
  },
  {
    "Nama":"TPS Jeruk",
    "Alamat":"Jl. Jeruk",
    "Kelurahan":"Jeruk",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3012869,
    "Longitude":112.6437428
  },
  {
    "Nama":"TPS Lakarsantri",
    "Alamat":"Jl. Lakarsantri",
    "Kelurahan":"Lakarsantri",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2978236,
    "Longitude":112.6335639
  },
  {
    "Nama":"TPS Lidah Kulon (Pengganti)",
    "Alamat":"Jl. Raya Lidah Kulon",
    "Kelurahan":"Lidah Kulon",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2997151,
    "Longitude":112.6555062
  },
  {
    "Nama":"TPS Wisma Lidah Kulon",
    "Alamat":"Perum Wisma Lidah Kulon",
    "Kelurahan":"Lidah Kulon",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2997151,
    "Longitude":112.6555062
  },
  {
    "Nama":"TPS Lidah Wetan Unesa",
    "Alamat":"Jl. Waduk Unesa",
    "Kelurahan":"Lidah Wetan",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3034214,
    "Longitude":112.6671884
  },
  {
    "Nama":"TPS Sumur Welut",
    "Alamat":"Jl. Sumberan Sumur Welut",
    "Kelurahan":"Sumur Welut",
    "Kecamatan":"Lakarsantri",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3260422,
    "Longitude":112.6724237
  },
  {
    "Nama":"TPS Sutorejo",
    "Alamat":"Jl. Sutorejo",
    "Kelurahan":"Dukuh Sutorejo",
    "Kecamatan":"Mulyorejo",
    "Kapasitas":33.0,
    "Volume Masuk":33.0,
    "Volume Dikelola":33.0,
    "Volume Sampah Diolah":33.0,
    "Volume Diangkut":33.0,
    "Latitude":-7.2568548,
    "Longitude":112.7917887
  },
  {
    "Nama":"TPS Kalijudan",
    "Alamat":"Jl. Kalijudan",
    "Kelurahan":"Kalijudan",
    "Kecamatan":"Mulyorejo",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2561843,
    "Longitude":112.7820897
  },
  {
    "Nama":"Pemilahan Superdepo Sutorejo",
    "Alamat":"Jl. Kalisari Timur - Sutorejo",
    "Kelurahan":"Kalisari",
    "Kecamatan":"Mulyorejo",
    "Kapasitas":20.0,
    "Volume Masuk":1427.5,
    "Volume Dikelola":1427.5,
    "Volume Sampah Diolah":691.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.2646746,
    "Longitude":112.8065049
  },
  {
    "Nama":"TPS Wisma Permai",
    "Alamat":"Jl. Wisma Permai",
    "Kelurahan":"Kalisari",
    "Kecamatan":"Mulyorejo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2646746,
    "Longitude":112.8065049
  },
  {
    "Nama":"TPS Kejawan Putih Tambak",
    "Alamat":"Jl. Kejawan Putih Tambak",
    "Kelurahan":"Kejawan Putih Tambak",
    "Kecamatan":"Mulyorejo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.2717595,
    "Longitude":112.8160468
  },
  {
    "Nama":"TPS Semut Kali",
    "Alamat":"Jl. Semut Kli",
    "Kelurahan":"Bongkaran",
    "Kecamatan":"Pabean Cantian",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2425638,
    "Longitude":112.7429766
  },
  {
    "Nama":"Landasan Kasuari",
    "Alamat":"Jl. Kasuari",
    "Kelurahan":"Krembangan Utara",
    "Kecamatan":"Pabean Cantian",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2287032,
    "Longitude":112.7353243
  },
  {
    "Nama":"TPS Pasar Babaan",
    "Alamat":"Jl. Kebalen Kulon",
    "Kelurahan":"Krembangan Utara",
    "Kecamatan":"Pabean Cantian",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2287032,
    "Longitude":112.7353243
  },
  {
    "Nama":"TPS Pesapen Pompa",
    "Alamat":"Jl. Pesapen Pompa",
    "Kelurahan":"Krembangan Utara",
    "Kecamatan":"Pabean Cantian",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2287032,
    "Longitude":112.7353243
  },
  {
    "Nama":"TPS Benteng",
    "Alamat":"Jl. Benteng",
    "Kelurahan":"Nyamplungan",
    "Kecamatan":"Pabean Cantian",
    "Kapasitas":42.0,
    "Volume Masuk":42.0,
    "Volume Dikelola":42.0,
    "Volume Sampah Diolah":42.0,
    "Volume Diangkut":42.0,
    "Latitude":-7.2317112,
    "Longitude":112.739687
  },
  {
    "Nama":"TPS Indrapura PLN",
    "Alamat":"Jl. Indrapura Jaya",
    "Kelurahan":"Perak Timur",
    "Kecamatan":"Pabean Cantian",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2285485,
    "Longitude":112.7313912
  },
  {
    "Nama":"TPS Babat Jerawat",
    "Alamat":"Jl. Dukuh Jerawat",
    "Kelurahan":"Babat Jerawat",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2404564,
    "Longitude":112.6294237
  },
  {
    "Nama":"Rukom Babat Jerawat",
    "Alamat":"Jl. Raya Babat Jerawat",
    "Kelurahan":"Babat Jerawat",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":3.9,
    "Volume Dikelola":3.9,
    "Volume Sampah Diolah":3.9,
    "Volume Diangkut":0.0,
    "Latitude":-7.2404564,
    "Longitude":112.6294237
  },
  {
    "Nama":"TPS Langkir",
    "Alamat":"Jl. Sendang Bulu",
    "Kelurahan":"Babat Jerawat",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2404564,
    "Longitude":112.6294237
  },
  {
    "Nama":"TPS Pondok Benowo Indah",
    "Alamat":"Perum Pondok Benowo Indah",
    "Kelurahan":"Babat Jerawat",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2404564,
    "Longitude":112.6294237
  },
  {
    "Nama":"TPS Benowo Krajan",
    "Alamat":"Jl. Benowo Krajan",
    "Kelurahan":"Benowo",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2339099,
    "Longitude":112.6152676
  },
  {
    "Nama":"TPS Pasar Benowo",
    "Alamat":"Jl. Raya Benowo",
    "Kelurahan":"Benowo",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2339099,
    "Longitude":112.6152676
  },
  {
    "Nama":"TPS Jurang Kuping",
    "Alamat":"Jl. Jurang Indah",
    "Kelurahan":"Pakal",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2377899,
    "Longitude":112.6200616
  },
  {
    "Nama":"TPS Pakal Madya",
    "Alamat":"Jl. Pakal Madya",
    "Kelurahan":"Pakal",
    "Kecamatan":"Pakal",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2377899,
    "Longitude":112.6200616
  },
  {
    "Nama":"TPS Pakal Sidorejo",
    "Alamat":"Jl. Pakal Sidorejo",
    "Kelurahan":"Pakal",
    "Kecamatan":"Pakal",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2377899,
    "Longitude":112.6200616
  },
  {
    "Nama":"TPS Pakal Timur",
    "Alamat":"Jl. Pakal Sumberan",
    "Kelurahan":"Pakal",
    "Kecamatan":"Pakal",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2377899,
    "Longitude":112.6200616
  },
  {
    "Nama":"TPS 3R Sumberejo",
    "Alamat":"Jl. Raya Sumberejo - Pakal",
    "Kelurahan":"Sumber Rejo",
    "Kecamatan":"Pakal",
    "Kapasitas":20.0,
    "Volume Masuk":20.0,
    "Volume Dikelola":20.0,
    "Volume Sampah Diolah":20.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.2168797,
    "Longitude":112.6141312
  },
  {
    "Nama":"TPS Sumberejo Krenuk",
    "Alamat":"Jl. Krenuk Sumberejo",
    "Kelurahan":"Sumberejo",
    "Kecamatan":"Pakal",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2293074,
    "Longitude":112.610012
  },
  {
    "Nama":"TPS Sumberejo Makam",
    "Alamat":"Jl. Sumberejo No. 2",
    "Kelurahan":"Sumberejo",
    "Kecamatan":"Pakal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2293074,
    "Longitude":112.610012
  },
  {
    "Nama":"TPS Wonokusumo Kidul",
    "Alamat":"Jl. Wonokusumo Kidul",
    "Kelurahan":"Pegirian",
    "Kecamatan":"Pegirian",
    "Kapasitas":39.6,
    "Volume Masuk":39.6,
    "Volume Dikelola":39.6,
    "Volume Sampah Diolah":39.6,
    "Volume Diangkut":39.6,
    "Latitude":-7.2261275,
    "Longitude":112.7494168
  },
  {
    "Nama":"TPS Makam Peneleh",
    "Alamat":"Jl. Makam Peneleh",
    "Kelurahan":"Peneleh",
    "Kecamatan":"Peneleh",
    "Kapasitas":23.1,
    "Volume Masuk":23.1,
    "Volume Dikelola":23.1,
    "Volume Sampah Diolah":23.1,
    "Volume Diangkut":23.1,
    "Latitude":-7.2532021,
    "Longitude":112.7408403
  },
  {
    "Nama":"TPS Romokalisari",
    "Alamat":"Jl. Romokalisari",
    "Kelurahan":"Romokalisari",
    "Kecamatan":"Romokalisari",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2169278,
    "Longitude":112.6458203
  },
  {
    "Nama":"TPS Rungkut Alang-Alang",
    "Alamat":"Jl. Kali Rungkut",
    "Kelurahan":"Kalirungkut",
    "Kecamatan":"Rungkut",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3199551,
    "Longitude":112.7676996
  },
  {
    "Nama":"TPS Medokan Ayu",
    "Alamat":"Jl. Medokan Asri Tengah",
    "Kelurahan":"Medokan Ayu",
    "Kecamatan":"Rungkut",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3256915,
    "Longitude":112.8008963
  },
  {
    "Nama":"Rukom Medokan Ayu",
    "Alamat":"Jl. Medokan Asri Tengah VI",
    "Kelurahan":"Medokan Ayu",
    "Kecamatan":"Rungkut",
    "Kapasitas":14.0,
    "Volume Masuk":3.0,
    "Volume Dikelola":3.0,
    "Volume Sampah Diolah":3.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.3256915,
    "Longitude":112.8008963
  },
  {
    "Nama":"TPS Kendal Sari Wonorejo",
    "Alamat":"Jl. Kendalsari ( Barat Kebun Bibit )",
    "Kelurahan":"Penjaringan Sari",
    "Kecamatan":"Rungkut",
    "Kapasitas":16.5,
    "Volume Masuk":16.5,
    "Volume Dikelola":16.5,
    "Volume Sampah Diolah":16.5,
    "Volume Diangkut":16.5,
    "Latitude":-7.3178367,
    "Longitude":112.7866834
  },
  {
    "Nama":"TPS Kendangsari Telkom",
    "Alamat":"Jl. Raya Kendangsari",
    "Kelurahan":"Penjaringan Sari",
    "Kecamatan":"Rungkut",
    "Kapasitas":33.0,
    "Volume Masuk":33.0,
    "Volume Dikelola":33.0,
    "Volume Sampah Diolah":33.0,
    "Volume Diangkut":33.0,
    "Latitude":-7.3178367,
    "Longitude":112.7866834
  },
  {
    "Nama":"TPS Penjaringan Sari",
    "Alamat":"Jl. Pandugo",
    "Kelurahan":"Penjaringansari",
    "Kecamatan":"Rungkut",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3178367,
    "Longitude":112.7866834
  },
  {
    "Nama":"TPS Rungkut Kidul (Pasar Pahing)",
    "Alamat":"Jl. Pasar Rungkut Kidul Pasar Pahing",
    "Kelurahan":"Rungkut Kidul",
    "Kecamatan":"Rungkut",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3293649,
    "Longitude":112.7722982
  },
  {
    "Nama":"TPS Rungkut Asri Merr",
    "Alamat":"Jl. Rungkut Asri",
    "Kelurahan":"Rungkut Kidul",
    "Kecamatan":"Rungkut",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3293649,
    "Longitude":112.7722982
  },
  {
    "Nama":"Rukom Rungkut Asri",
    "Alamat":"Jl. Rungkut Asri",
    "Kelurahan":"Rungkut Kidul",
    "Kecamatan":"Rungkut",
    "Kapasitas":20.0,
    "Volume Masuk":13.6,
    "Volume Dikelola":13.6,
    "Volume Sampah Diolah":13.6,
    "Volume Diangkut":0.0,
    "Latitude":-7.3293649,
    "Longitude":112.7722982
  },
  {
    "Nama":"Rukom Rungkut Asri Timur (Merr)",
    "Alamat":"Jl. Rungkut Asri Timur III",
    "Kelurahan":"Rungkut Kidul",
    "Kecamatan":"Rungkut",
    "Kapasitas":40.0,
    "Volume Masuk":13.2,
    "Volume Dikelola":13.2,
    "Volume Sampah Diolah":13.2,
    "Volume Diangkut":0.0,
    "Latitude":-7.3293649,
    "Longitude":112.7722982
  },
  {
    "Nama":"Rukom Wonorejo No. 2",
    "Alamat":"Jl. Kendalsari - Wonorejo (Area Kebun Bibit Wonorejo)",
    "Kelurahan":"Wonorejo",
    "Kecamatan":"Rungkut",
    "Kapasitas":60.0,
    "Volume Masuk":26.5,
    "Volume Dikelola":26.5,
    "Volume Sampah Diolah":26.5,
    "Volume Diangkut":0.0,
    "Latitude":-7.3102812,
    "Longitude":112.815267
  },
  {
    "Nama":"Rukom Wonorejo",
    "Alamat":"Jl. Kendalsari Kebun Bibit Wonorejo",
    "Kelurahan":"Wonorejo",
    "Kecamatan":"Rungkut",
    "Kapasitas":20.0,
    "Volume Masuk":0.1,
    "Volume Dikelola":0.1,
    "Volume Sampah Diolah":0.1,
    "Volume Diangkut":0.0,
    "Latitude":-7.3102812,
    "Longitude":112.815267
  },
  {
    "Nama":"TPS Wonorejo",
    "Alamat":"Jl. Raya Wonorejo",
    "Kelurahan":"Wonorejo",
    "Kecamatan":"Rungkut",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.3102812,
    "Longitude":112.815267
  },
  {
    "Nama":"TPS Alas Malang",
    "Alamat":"Jl. Alas Malang",
    "Kelurahan":"Bringin",
    "Kecamatan":"Sambikerep",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2644698,
    "Longitude":112.6440689
  },
  {
    "Nama":"TPS Bringin",
    "Alamat":"Jl. Bringin",
    "Kelurahan":"Bringin",
    "Kecamatan":"Sambikerep",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2644698,
    "Longitude":112.6440689
  },
  {
    "Nama":"TPS Sawo",
    "Alamat":"Jl. Sawo No. 6",
    "Kelurahan":"Bringin",
    "Kecamatan":"Sambikerep",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2644698,
    "Longitude":112.6440689
  },
  {
    "Nama":"TPS Candi Lontar",
    "Alamat":"Jl. Lempung Sari",
    "Kelurahan":"Lontar",
    "Kecamatan":"Sambikerep",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2782064,
    "Longitude":112.6684446
  },
  {
    "Nama":"TPS Lempung Perdana",
    "Alamat":"Jl. Lontar",
    "Kelurahan":"Lontar",
    "Kecamatan":"Sambikerep",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2782064,
    "Longitude":112.6684446
  },
  {
    "Nama":"TPS Kuwukan",
    "Alamat":"Jl. Kuwukan Sambikerep",
    "Kelurahan":"Sambikerep",
    "Kecamatan":"Sambikerep",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2771669,
    "Longitude":112.6523073
  },
  {
    "Nama":"TPS Simo Katrungan",
    "Alamat":"Jl. Simo Katrungan",
    "Kelurahan":"Banyu Urip",
    "Kecamatan":"Sawahan",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2721443,
    "Longitude":112.7195078
  },
  {
    "Nama":"TPS Kembang Kuning",
    "Alamat":"Jl. Kembang Kuning",
    "Kelurahan":"Darmo",
    "Kecamatan":"Sawahan",
    "Kapasitas":42.0,
    "Volume Masuk":42.0,
    "Volume Dikelola":42.0,
    "Volume Sampah Diolah":42.0,
    "Volume Diangkut":42.0,
    "Latitude":-7.2907428,
    "Longitude":112.7179115
  },
  {
    "Nama":"Landasan Bintang Diponggo",
    "Alamat":"Jl. Bintang Diponggo",
    "Kelurahan":"Pakis",
    "Kecamatan":"Sawahan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2864498,
    "Longitude":112.7222672
  },
  {
    "Nama":"TPS Bukit Barisan",
    "Alamat":"Jl. Bukit Barisan",
    "Kelurahan":"Petemon",
    "Kecamatan":"Sawahan",
    "Kapasitas":59.4,
    "Volume Masuk":59.4,
    "Volume Dikelola":59.4,
    "Volume Sampah Diolah":59.4,
    "Volume Diangkut":59.4,
    "Latitude":-7.2613953,
    "Longitude":112.7184525
  },
  {
    "Nama":"TPS Petemon Kuburan",
    "Alamat":"Jl. Petemon Kuburan",
    "Kelurahan":"Petemon",
    "Kecamatan":"Sawahan",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2613953,
    "Longitude":112.7184525
  },
  {
    "Nama":"TPS Simo Kwagean (Mataram Utara)",
    "Alamat":"Jl. Makam Putat",
    "Kelurahan":"Putat Jaya",
    "Kecamatan":"Sawahan",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2766812,
    "Longitude":112.7163307
  },
  {
    "Nama":"TPS Makam Mataram",
    "Alamat":"Jl. Makam Putat Jaya",
    "Kelurahan":"Putat Jaya",
    "Kecamatan":"Sawahan",
    "Kapasitas":56.0,
    "Volume Masuk":56.0,
    "Volume Dikelola":56.0,
    "Volume Sampah Diolah":56.0,
    "Volume Diangkut":56.0,
    "Latitude":-7.2766812,
    "Longitude":112.7163307
  },
  {
    "Nama":"Rukom Putat",
    "Alamat":"Jl. Makam Putat Jaya",
    "Kelurahan":"Putat Jaya",
    "Kecamatan":"Sawahan",
    "Kapasitas":14.0,
    "Volume Masuk":0.4,
    "Volume Dikelola":0.4,
    "Volume Sampah Diolah":0.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.2766812,
    "Longitude":112.7163307
  },
  {
    "Nama":"TPS Pegirian",
    "Alamat":"Jl. Pegirian",
    "Kelurahan":"Sidotopo",
    "Kecamatan":"Semampir",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2299725,
    "Longitude":112.7505235
  },
  {
    "Nama":"TPS Jati Purwo",
    "Alamat":"Jl. Jati Purwo",
    "Kelurahan":"Ujung",
    "Kecamatan":"Semampir",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2121829,
    "Longitude":112.7440507
  },
  {
    "Nama":"TPS Jati Srono",
    "Alamat":"Jl. Jati Srono",
    "Kelurahan":"Ujung",
    "Kecamatan":"Semampir",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2121829,
    "Longitude":112.7440507
  },
  {
    "Nama":"TPS Mrutu Kalianyar",
    "Alamat":"Jl. Mrutu Kalianyar",
    "Kelurahan":"Wonokusumo",
    "Kecamatan":"Semampir",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2181412,
    "Longitude":112.7546814
  },
  {
    "Nama":"TPS Kendung BDH",
    "Alamat":"Jl. Raya Kendung Benowo",
    "Kelurahan":"Sememi",
    "Kecamatan":"Sememi",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.250198,
    "Longitude":112.6419156
  },
  {
    "Nama":"TPS Kendung Makam",
    "Alamat":"Jl. Sememi",
    "Kelurahan":"Sememi",
    "Kecamatan":"Sememi",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.250198,
    "Longitude":112.6419156
  },
  {
    "Nama":"Landasan Kertopaten",
    "Alamat":"Jl. Kertopaten",
    "Kelurahan":"Sidodadi",
    "Kecamatan":"Simokerto",
    "Kapasitas":42.0,
    "Volume Masuk":42.0,
    "Volume Dikelola":42.0,
    "Volume Sampah Diolah":42.0,
    "Volume Diangkut":42.0,
    "Latitude":-7.2370472,
    "Longitude":112.7477525
  },
  {
    "Nama":"TPS Kapasan",
    "Alamat":"Jl. Pasar Kapasan",
    "Kelurahan":"Sidodadi",
    "Kecamatan":"Simokerto",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2370472,
    "Longitude":112.7477525
  },
  {
    "Nama":"TPS Simolawang",
    "Alamat":"Jl. Simolawang",
    "Kelurahan":"Simolawang",
    "Kecamatan":"Simokerto",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2336373,
    "Longitude":112.7483635
  },
  {
    "Nama":"TPS Tambak Rejo",
    "Alamat":"Jl. Tambak Rejo",
    "Kelurahan":"Tambak Rejo",
    "Kecamatan":"Simokerto",
    "Kapasitas":52.8,
    "Volume Masuk":52.8,
    "Volume Dikelola":52.8,
    "Volume Sampah Diolah":52.8,
    "Volume Diangkut":52.8,
    "Latitude":-7.2435993,
    "Longitude":112.7579716
  },
  {
    "Nama":"TPS Gebang Putih",
    "Alamat":"Jl. Gebang Putih",
    "Kelurahan":"Gebang Putih",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2817272,
    "Longitude":112.7869931
  },
  {
    "Nama":"TPS Its",
    "Alamat":"Jl. Arif Rahman Hakim",
    "Kelurahan":"Keputih",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.295096,
    "Longitude":112.7927717
  },
  {
    "Nama":"TPS Iplt Keputih",
    "Alamat":"Jl. Keputih Tegal",
    "Kelurahan":"Keputih",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":12.0,
    "Latitude":-7.295096,
    "Longitude":112.7927717
  },
  {
    "Nama":"Rukom Iplt Keputih",
    "Alamat":"Jl. Keputih Tegal (Area Iplt Keputih)",
    "Kelurahan":"Keputih",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":6.5,
    "Volume Dikelola":6.5,
    "Volume Sampah Diolah":6.5,
    "Volume Diangkut":0.0,
    "Latitude":-7.295096,
    "Longitude":112.7927717
  },
  {
    "Nama":"Rukom Liponsos Keputih",
    "Alamat":"Jl. Keputih Tegal No. 32",
    "Kelurahan":"Keputih",
    "Kecamatan":"Sukolilo",
    "Kapasitas":8.0,
    "Volume Masuk":0.1,
    "Volume Dikelola":0.1,
    "Volume Sampah Diolah":0.1,
    "Volume Diangkut":0.0,
    "Latitude":-7.295096,
    "Longitude":112.7927717
  },
  {
    "Nama":"TPS Klampis Ngasem",
    "Alamat":"Jl. Klampis Ngasem",
    "Kelurahan":"Klampis Ngasem",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.288672,
    "Longitude":112.777086
  },
  {
    "Nama":"TPS Semolowaru Bahari (Tpu Keputih)",
    "Alamat":"Jl. Medokan Keputih",
    "Kelurahan":"Medokan Semampir",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3062527,
    "Longitude":112.7847949
  },
  {
    "Nama":"TPS Medokan Semampir",
    "Alamat":"Jl. Medokan Semampir",
    "Kelurahan":"Medokan Semampir",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3062527,
    "Longitude":112.7847949
  },
  {
    "Nama":"TPS Buktong",
    "Alamat":"Jl. Menur - Manyar",
    "Kelurahan":"Menur Pumpungan",
    "Kecamatan":"Sukolilo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.2919238,
    "Longitude":112.7672637
  },
  {
    "Nama":"TPS Aspol Nginden Intan",
    "Alamat":"Jl. Nginden Intan Timur",
    "Kelurahan":"Nginden Jangkungan",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3041049,
    "Longitude":112.7673107
  },
  {
    "Nama":"Rukom Nginden Jangkungan",
    "Alamat":"Jl. Nginden Jangkungan",
    "Kelurahan":"Nginden Jangkungan",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.3041049,
    "Longitude":112.7673107
  },
  {
    "Nama":"TPS Semolowaru",
    "Alamat":"Jl. Semolowaru",
    "Kelurahan":"Semolowaru",
    "Kecamatan":"Sukolilo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3004075,
    "Longitude":112.7812994
  },
  {
    "Nama":"TPS Putat Gede",
    "Alamat":"Jl. Putat Gede Barat",
    "Kelurahan":"Putat Gede",
    "Kecamatan":"Sukomanunggal",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2872531,
    "Longitude":112.7017346
  },
  {
    "Nama":"TPS Simohilir",
    "Alamat":"Jl. Simo Hilir",
    "Kelurahan":"Simo Mulyo",
    "Kecamatan":"Sukomanunggal",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2712758,
    "Longitude":112.7033681
  },
  {
    "Nama":"TPS Simorukun",
    "Alamat":"Jl. Simo Mulyo",
    "Kelurahan":"Simo Mulyo",
    "Kecamatan":"Sukomanunggal",
    "Kapasitas":33.0,
    "Volume Masuk":33.0,
    "Volume Dikelola":33.0,
    "Volume Sampah Diolah":33.0,
    "Volume Diangkut":33.0,
    "Latitude":-7.2712758,
    "Longitude":112.7033681
  },
  {
    "Nama":"Rukom Sonokwijenan",
    "Alamat":"Jl. Darmo Baru Barat XII",
    "Kelurahan":"Sonokwijenan",
    "Kecamatan":"Sukomanunggal",
    "Kapasitas":20.0,
    "Volume Masuk":3.9,
    "Volume Dikelola":3.9,
    "Volume Sampah Diolah":3.9,
    "Volume Diangkut":0.0,
    "Latitude":-7.2798775,
    "Longitude":112.6993551
  },
  {
    "Nama":"TPS Sonokwijenan",
    "Alamat":"Jl. Sonokwijenan",
    "Kelurahan":"Sonokwijenan",
    "Kecamatan":"Sukomanunggal",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2798775,
    "Longitude":112.6993551
  },
  {
    "Nama":"TPS Sukomanunggal",
    "Alamat":"Jl. Suko Manunggal",
    "Kelurahan":"Sukomanunggal",
    "Kecamatan":"Sukomanunggal",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2617671,
    "Longitude":112.6973817
  },
  {
    "Nama":"TPS Candi Puro",
    "Alamat":"Jl. Candipuro",
    "Kelurahan":"Pacar Keling",
    "Kecamatan":"Tambaksari",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2613668,
    "Longitude":112.7553135
  },
  {
    "Nama":"TPS Gubeng Masjid",
    "Alamat":"Jl. Gubeng Masjid",
    "Kelurahan":"Pacar Keling",
    "Kecamatan":"Tambaksari",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2613668,
    "Longitude":112.7553135
  },
  {
    "Nama":"TPS Gubeng Masjid Pasar",
    "Alamat":"Jl. Gubeng Masjid",
    "Kelurahan":"Pacar Keling",
    "Kecamatan":"Tambaksari",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2613668,
    "Longitude":112.7553135
  },
  {
    "Nama":"TPS Pasar Pacar Keling",
    "Alamat":"Jl. Pacar Keling",
    "Kelurahan":"Pacar Keling",
    "Kecamatan":"Tambaksari",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2613668,
    "Longitude":112.7553135
  },
  {
    "Nama":"TPS Petojo",
    "Alamat":"Jl. Petojo",
    "Kelurahan":"Pacar Keling",
    "Kecamatan":"Tambaksari",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2613668,
    "Longitude":112.7553135
  },
  {
    "Nama":"TPS Bogen",
    "Alamat":"Jl. Bogen Tambaksari",
    "Kelurahan":"Ploso",
    "Kecamatan":"Tambaksari",
    "Kapasitas":39.6,
    "Volume Masuk":39.6,
    "Volume Dikelola":39.6,
    "Volume Sampah Diolah":39.6,
    "Volume Diangkut":39.6,
    "Latitude":-7.2537739,
    "Longitude":112.7716601
  },
  {
    "Nama":"TPS Balongsari",
    "Alamat":"Jl. Balongsari",
    "Kelurahan":"Balongsari",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2516604,
    "Longitude":112.6796715
  },
  {
    "Nama":"TPS 3R Banjarsugihan",
    "Alamat":"Jl. Banjarsugihan Gang Rolax",
    "Kelurahan":"Banjar Sugihan",
    "Kecamatan":"Tandes",
    "Kapasitas":20.0,
    "Volume Masuk":0.0,
    "Volume Dikelola":0.0,
    "Volume Sampah Diolah":0.0,
    "Volume Diangkut":0.0,
    "Latitude":-7.2526092,
    "Longitude":112.659658
  },
  {
    "Nama":"TPS Tengger",
    "Alamat":"Jl. Tengger Raya",
    "Kelurahan":"Banjar Sugihan",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2526092,
    "Longitude":112.659658
  },
  {
    "Nama":"TPS Karangpoh",
    "Alamat":"Jl. Darmo Indah Barat II",
    "Kelurahan":"Karangpoh",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2661933,
    "Longitude":112.6822479
  },
  {
    "Nama":"TPS Tubanan",
    "Alamat":"Jl. Tubanan",
    "Kelurahan":"Karangpoh",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2661933,
    "Longitude":112.6822479
  },
  {
    "Nama":"TPS Manukan Kulon",
    "Alamat":"Jl. Manukan Kulon",
    "Kelurahan":"Manukan Kulon",
    "Kecamatan":"Tandes",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2600153,
    "Longitude":112.6664211
  },
  {
    "Nama":"TPS Manukan Kulon Baru",
    "Alamat":"Jl. Manukan Kulon",
    "Kelurahan":"Manukan Kulon",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2600153,
    "Longitude":112.6664211
  },
  {
    "Nama":"TPS Buntaran",
    "Alamat":"Jl. Buntaran",
    "Kelurahan":"Manukan Wetan",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2466469,
    "Longitude":112.6695467
  },
  {
    "Nama":"TPS Manukan Telaga",
    "Alamat":"Jl. Manukan Peni VII",
    "Kelurahan":"Manukan Wetan",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2466469,
    "Longitude":112.6695467
  },
  {
    "Nama":"TPS Manukan Wetan",
    "Alamat":"Jl. Sikatan",
    "Kelurahan":"Manukan Wetan",
    "Kecamatan":"Tandes",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.2466469,
    "Longitude":112.6695467
  },
  {
    "Nama":"TPS Darmo Indah",
    "Alamat":"Jl. Darmo Indah",
    "Kelurahan":"Tandes",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2588965,
    "Longitude":112.6870227
  },
  {
    "Nama":"Rukom Tubanan",
    "Alamat":"Jl. Tubanan Tandes",
    "Kelurahan":"Tandes",
    "Kecamatan":"Tandes",
    "Kapasitas":14.0,
    "Volume Masuk":0.9,
    "Volume Dikelola":0.9,
    "Volume Sampah Diolah":0.9,
    "Volume Diangkut":0.0,
    "Latitude":-7.2588965,
    "Longitude":112.6870227
  },
  {
    "Nama":"Rukom Keputran",
    "Alamat":"Jl. Keputran",
    "Kelurahan":"Keputran",
    "Kecamatan":"Tegalsari",
    "Kapasitas":14.0,
    "Volume Masuk":11.3,
    "Volume Dikelola":11.3,
    "Volume Sampah Diolah":11.3,
    "Volume Diangkut":0.0,
    "Latitude":-7.2822916,
    "Longitude":112.7427724
  },
  {
    "Nama":"TPS Pasar Keputran",
    "Alamat":"Jl. Keputran Utara",
    "Kelurahan":"Keputran",
    "Kecamatan":"Tegalsari",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2822916,
    "Longitude":112.7427724
  },
  {
    "Nama":"TPS Dinoyo",
    "Alamat":"Jl. Siliwangi",
    "Kelurahan":"Keputran",
    "Kecamatan":"Tegalsari",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.2822916,
    "Longitude":112.7427724
  },
  {
    "Nama":"TPS Kedondong",
    "Alamat":"Jl. Kedondong",
    "Kelurahan":"Tegalsari",
    "Kecamatan":"Tegalsari",
    "Kapasitas":42.0,
    "Volume Masuk":42.0,
    "Volume Dikelola":42.0,
    "Volume Sampah Diolah":42.0,
    "Volume Diangkut":42.0,
    "Latitude":-7.2709683,
    "Longitude":112.7369761
  },
  {
    "Nama":"TPS Pasar Kembang",
    "Alamat":"Jl. Wonorejo III (Pasar Kembang)",
    "Kelurahan":"Wonorejo",
    "Kecamatan":"Tegalsari",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.2706933,
    "Longitude":112.7317884
  },
  {
    "Nama":"TPS Kutisari PLN",
    "Alamat":"Jl. Kutisari PLN",
    "Kelurahan":"Kutisari",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3359221,
    "Longitude":112.7483208
  },
  {
    "Nama":"TPS Prapen DKK",
    "Alamat":"Jl. Jemur Sari DKK",
    "Kelurahan":"Panjang Jiwo",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.3121667,
    "Longitude":112.7614965
  },
  {
    "Nama":"TPS Prapen",
    "Alamat":"Jl. Raya Prapen",
    "Kelurahan":"Panjang Jiwo",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.3121667,
    "Longitude":112.7614965
  },
  {
    "Nama":"TPS Prapen Sisi Timur (Depan Graha Track)",
    "Alamat":"Jl. Raya Prapen (Sisi Timur)",
    "Kelurahan":"Panjang Jiwo",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.3121667,
    "Longitude":112.7614965
  },
  {
    "Nama":"TPS Raya Prapen",
    "Alamat":"Jl. Raya Prapen Sisi Barat",
    "Kelurahan":"Panjang Jiwo",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.3121667,
    "Longitude":112.7614965
  },
  {
    "Nama":"TPS 3R Tenggilis",
    "Alamat":"Jl. Tenggilis Barat I",
    "Kelurahan":"Tenggilis Mejoyo",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":20.0,
    "Volume Masuk":614.9,
    "Volume Dikelola":614.9,
    "Volume Sampah Diolah":390.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.3198073,
    "Longitude":112.7569099
  },
  {
    "Nama":"Rukom Tenggilis Rayon Taman",
    "Alamat":"Jl. Tenggilis Tengah",
    "Kelurahan":"Tenggilis Mejoyo",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":14.0,
    "Volume Masuk":4.3,
    "Volume Dikelola":4.3,
    "Volume Sampah Diolah":4.3,
    "Volume Diangkut":0.0,
    "Latitude":-7.3198073,
    "Longitude":112.7569099
  },
  {
    "Nama":"Rukom Tenggilis Utara",
    "Alamat":"Jl. Tenggilis Utara",
    "Kelurahan":"Tenggilis Mejoyo",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":14.0,
    "Volume Masuk":3.4,
    "Volume Dikelola":3.4,
    "Volume Sampah Diolah":3.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.3198073,
    "Longitude":112.7569099
  },
  {
    "Nama":"TPS Tenggilis Utara",
    "Alamat":"Jl. Tenggilis Utara",
    "Kelurahan":"Tenggilis Utara",
    "Kecamatan":"Tenggilis Mejoyo",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3164081,
    "Longitude":112.7550217
  },
  {
    "Nama":"TPS Babatan Indah",
    "Alamat":"Jl. Babatan Indah",
    "Kelurahan":"Babatan",
    "Kecamatan":"Wiyung",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3021334,
    "Longitude":112.6811362
  },
  {
    "Nama":"Rukom Balas Klumprik",
    "Alamat":"Jl. Balas Klumprik Pdam",
    "Kelurahan":"Balas Klumprik",
    "Kecamatan":"Wiyung",
    "Kapasitas":14.0,
    "Volume Masuk":3.4,
    "Volume Dikelola":3.4,
    "Volume Sampah Diolah":3.4,
    "Volume Diangkut":0.0,
    "Latitude":-7.3270194,
    "Longitude":112.6873078
  },
  {
    "Nama":"TPS Balas Klumprik",
    "Alamat":"Jl. Koterm Balas Klumprik",
    "Kelurahan":"Balas Klumprik",
    "Kecamatan":"Wiyung",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3270194,
    "Longitude":112.6873078
  },
  {
    "Nama":"TPS Pondok Manggala",
    "Alamat":"Jl. Pondok Mnggala",
    "Kelurahan":"Balas Klumprik",
    "Kecamatan":"Wiyung",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3270194,
    "Longitude":112.6873078
  },
  {
    "Nama":"TPS Wiyung Kramat",
    "Alamat":"Jl. Kramat Wiyung",
    "Kelurahan":"Jajar Tunggal",
    "Kecamatan":"Wiyung",
    "Kapasitas":8.0,
    "Volume Masuk":8.0,
    "Volume Dikelola":8.0,
    "Volume Sampah Diolah":8.0,
    "Volume Diangkut":8.0,
    "Latitude":-7.3090046,
    "Longitude":112.7057276
  },
  {
    "Nama":"TPS Gogor \/ Jajar Tunggal",
    "Alamat":"Jl. Mastrip",
    "Kelurahan":"Jajar Tunggal",
    "Kecamatan":"Wiyung",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3090046,
    "Longitude":112.7057276
  },
  {
    "Nama":"TPS Pasar Wiyung",
    "Alamat":"Jl. Menganti Wiyung",
    "Kelurahan":"Wiyung",
    "Kecamatan":"Wiyung",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3109179,
    "Longitude":112.693824
  },
  {
    "Nama":"TPS Tpi Wiyung",
    "Alamat":"Jl. Tpi Wiyung",
    "Kelurahan":"Wiyung",
    "Kecamatan":"Wiyung",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3109179,
    "Longitude":112.693824
  },
  {
    "Nama":"TPS Jemur Wonosari",
    "Alamat":"Jl. Jemur Wonosari",
    "Kelurahan":"Jemur Wonosari",
    "Kecamatan":"Wonocolo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.3240169,
    "Longitude":112.7379509
  },
  {
    "Nama":"TPS Siwalankerto",
    "Alamat":"Jl. Siwalan Kerto",
    "Kelurahan":"Siwalankerto",
    "Kecamatan":"Wonocolo",
    "Kapasitas":26.4,
    "Volume Masuk":25.4,
    "Volume Dikelola":25.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":25.4,
    "Latitude":-7.3356142,
    "Longitude":112.7359922
  },
  {
    "Nama":"TPS Pasar Beras Bendul Merisi",
    "Alamat":"Jl. Bendul Merisi",
    "Kelurahan":"Bendul Merisi",
    "Kecamatan":"Wonokromo",
    "Kapasitas":28.0,
    "Volume Masuk":28.0,
    "Volume Dikelola":28.0,
    "Volume Sampah Diolah":28.0,
    "Volume Diangkut":28.0,
    "Latitude":-7.3071908,
    "Longitude":112.7360777
  },
  {
    "Nama":"Depo Bendul Merisi",
    "Alamat":"Jl. Bendul Merisi Selatan",
    "Kelurahan":"Bendul Merisi",
    "Kecamatan":"Wonokromo",
    "Kapasitas":42.0,
    "Volume Masuk":42.0,
    "Volume Dikelola":42.0,
    "Volume Sampah Diolah":42.0,
    "Volume Diangkut":42.0,
    "Latitude":-7.3071908,
    "Longitude":112.7360777
  },
  {
    "Nama":"TPS Taman Ketampon",
    "Alamat":"Jl. Taman Ketampon",
    "Kelurahan":"Darmo",
    "Kecamatan":"Wonokromo",
    "Kapasitas":23.0,
    "Volume Masuk":23.0,
    "Volume Dikelola":23.0,
    "Volume Sampah Diolah":23.0,
    "Volume Diangkut":23.0,
    "Latitude":-7.2894287,
    "Longitude":112.7332404
  },
  {
    "Nama":"TPS Jagir",
    "Alamat":"Jl. Jagir",
    "Kelurahan":"Jagir",
    "Kecamatan":"Wonokromo",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.3058685,
    "Longitude":112.7424765
  },
  {
    "Nama":"TPS Ngagel",
    "Alamat":"Jl. Ngagel",
    "Kelurahan":"Ngagel",
    "Kecamatan":"Wonokromo",
    "Kapasitas":19.8,
    "Volume Masuk":19.8,
    "Volume Dikelola":19.8,
    "Volume Sampah Diolah":19.8,
    "Volume Diangkut":19.8,
    "Latitude":-7.290469,
    "Longitude":112.7451258
  },
  {
    "Nama":"TPS Bratang Lapangan",
    "Alamat":"Jl. Bratang Lapangan",
    "Kelurahan":"Ngagel Rejo",
    "Kecamatan":"Wonokromo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":12.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2978653,
    "Longitude":112.7492322
  },
  {
    "Nama":"TPS Ngagel Dadi",
    "Alamat":"Jl. Ngagel Dadi III",
    "Kelurahan":"Ngagel Rejo",
    "Kecamatan":"Wonokromo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2978653,
    "Longitude":112.7492322
  },
  {
    "Nama":"TPS Joyoboyo",
    "Alamat":"Jl. Joyoboyo Gunungsari",
    "Kelurahan":"Sawunggaling",
    "Kecamatan":"Wonokromo",
    "Kapasitas":26.4,
    "Volume Masuk":26.4,
    "Volume Dikelola":26.4,
    "Volume Sampah Diolah":26.4,
    "Volume Diangkut":26.4,
    "Latitude":-7.2985439,
    "Longitude":112.7265924
  },
  {
    "Nama":"TPS Wonoboyo",
    "Alamat":"Jl. Wonoboyo Batanghari",
    "Kelurahan":"Sawunggaling",
    "Kecamatan":"Wonokromo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.2985439,
    "Longitude":112.7265924
  },
  {
    "Nama":"TPS Jetis Kulon",
    "Alamat":"Jl. Jetis Kulon",
    "Kelurahan":"Wonokromo",
    "Kecamatan":"Wonokromo",
    "Kapasitas":14.0,
    "Volume Masuk":14.0,
    "Volume Dikelola":14.0,
    "Volume Sampah Diolah":14.0,
    "Volume Diangkut":14.0,
    "Latitude":-7.3020554,
    "Longitude":112.7392222
  }
]